import * as vscode from 'vscode';
import * as path from 'path';
import { AIDetector } from '../core/aiDetector';
import { GitAnalyzer } from '../core/gitAnalyzer';
import { TeamStatsManager } from '../core/teamStats';
import { MarkPatternManager } from '../core/markPatternManager';

export class MarkCommands {
  constructor(
    private gitAnalyzer: GitAnalyzer,
    private statsManager: TeamStatsManager
  ) {}

  async markAsAI(): Promise<void> {
    const editor = vscode.window.activeTextEditor;
    if (!editor) {
      vscode.window.showWarningMessage('请先打开一个文件');
      return;
    }
    
    const selection = editor.selection;
    if (selection.isEmpty) {
      vscode.window.showWarningMessage('请先选中要标记的代码');
      return;
    }
    
    const config = vscode.workspace.getConfiguration('aiCodeTracker');
    const markFormat = config.get<string>('markFormat', 'comment');
    
    // 询问标记风格（根据规范文档）
    const markStyle = await vscode.window.showQuickPick([
      { label: '头部注释', description: '在文件头部添加 JSDoc/HTML 格式的 AI 标记', value: 'header' },
      { label: '行内注释', description: '在代码行末尾添加 // @ai-generated: YYYY-MM-DD 说明', value: 'inline' },
      { label: '块标记', description: '用 @ai-generated-start / @ai-generated-end 包裹代码块', value: 'block' },
      { label: 'JSON 标记文件', description: '创建 .generated 标记文件（仅 JSON）', value: 'json-marker' },
      { label: '标准格式', description: '[AI-GEN] model=xxx', value: 'tag' },
    ], { placeHolder: '选择标记风格（按规范文档）' });
    
    if (!markStyle) return;
    
    // 块标记不需要设置 model，使用作者作为标识
    let model = '';
    if (markStyle.value !== 'block') {
      const modelInput = await vscode.window.showInputBox({
        prompt: '请输入AI模型名称',
        placeHolder: 'deepseek-v3, copilot, chatgpt...',
        value: 'deepseek-v3'
      });
      
      if (!modelInput) return;
      model = modelInput;
    }
    
    const patternManager = MarkPatternManager.getInstance();
    
    // 获取作者信息
    let author: string = '';
    const { getCurrentGitUser } = await import('../utils/git');
    const user = await getCurrentGitUser();
    author = user.email.split('@')[0] || user.name.split(' ')[0] || 'unknown';
    
    let description = await vscode.window.showInputBox({
      prompt: '输入修改说明（可选）',
      placeHolder: '例如: 添加用户管理功能'
    });
    
    // JSON 文件特殊处理
    if (markStyle.value === 'json-marker') {
      const filePath = editor.document.fileName;
      if (!filePath.endsWith('.json')) {
        vscode.window.showWarningMessage('JSON 标记文件只能用于 .json 文件');
        return;
      }
      
      const markerPath = filePath + '.generated';
      const markerContent = `
        @ai-generated by ${author}
        @date ${new Date().toISOString().split('T')[0]}
        @description ${description || 'AI 生成的 JSON 配置'}
      `;
      
      await vscode.workspace.fs.writeFile(
        vscode.Uri.file(markerPath),
        Buffer.from(markerContent, 'utf-8')
      );
      
      vscode.window.showInformationMessage(`✅ 已创建标记文件: ${path.basename(markerPath)}`);
      await this.gitAnalyzer.analyzeFile(filePath);
      return;
    }
    
    // 生成标记文本
    let markText = '';
    
    if (markStyle.value === 'block') {
      // 块标记格式：分别生成开始和结束标记
      const commentSyntax = AIDetector.getCommentSyntax(editor.document.languageId);
      const formattedDate = new Date().toISOString().split('T')[0];
      const desc = description || '';
      
      const startMark = `${commentSyntax} @ai-generated-start by ${author} ${formattedDate}${desc ? ' ' + desc : ''}`;
      const endMark = `${commentSyntax} @ai-generated-end`;
      
      // 获取选中代码第一行的缩进
      const firstLineText = editor.document.lineAt(selection.start.line).text;
      const indentMatch = firstLineText.match(/^(\s*)/);
      const indent = indentMatch ? indentMatch[1] : '';
      
      await editor.edit(editBuilder => {
        // 在选中代码开始前插入开始标记（保持相同缩进）
        editBuilder.insert(new vscode.Position(selection.start.line, 0), indent + startMark + '\n');
        // 在选中代码结束后插入结束标记（保持相同缩进）
        const endLineText = editor.document.lineAt(selection.end.line).text;
        editBuilder.insert(new vscode.Position(selection.end.line, endLineText.length), '\n' + indent + endMark);
      });
      
      vscode.window.showInformationMessage(`✅ 已标记代码块为AI生成 (by ${author})`);
      await this.gitAnalyzer.analyzeFile(editor.document.fileName);
      return;
    }
    
    // 头部注释或行内注释
    markText = patternManager.generateAIMark(editor.document.languageId, model, {
      format: markStyle.value as any,
      author: author,
      date: new Date(),
      description: description || undefined
    });
    
    if (markStyle.value === 'header') {
      // 头部注释：插入到文件开头
      const firstLine = new vscode.Position(0, 0);
      await editor.edit(editBuilder => {
        editBuilder.insert(firstLine, markText + '\n\n');
      });
    } else {
      // 行内注释：插入到选中行上方（保持相同缩进）
      const firstLineText = editor.document.lineAt(selection.start.line).text;
      const indentMatch = firstLineText.match(/^(\s*)/);
      const indent = indentMatch ? indentMatch[1] : '';
      
      await editor.edit(editBuilder => {
        editBuilder.insert(new vscode.Position(selection.start.line, 0), indent + markText + '\n');
      });
    }
    
    await this.gitAnalyzer.analyzeFile(editor.document.fileName);
    vscode.window.showInformationMessage(`✅ 已标记选中代码为AI生成 (${model})`);
  }

  async markAsHuman(): Promise<void> {
    const editor = vscode.window.activeTextEditor;
    if (!editor) {
      vscode.window.showWarningMessage('请先打开一个文件');
      return;
    }
    
    const selection = editor.selection;
    if (selection.isEmpty) {
      vscode.window.showWarningMessage('请先选中要标记的代码');
      return;
    }
    
    // 询问标记风格
    const markStyle = await vscode.window.showQuickPick([
      { label: '行内标记', description: '在选中代码上方添加单行人工标记', value: 'inline' },
      { label: '块级标记', description: '用 @human-start / @human-end 包裹代码块', value: 'block' },
    ], { placeHolder: '选择人工代码标记风格' });
    
    if (!markStyle) return;
    
    // 自动获取 Git 作者名
    let author: string = '';
    const { getCurrentGitUser } = await import('../utils/git');
    const user = await getCurrentGitUser();
    author = user.email.split('@')[0] || user.name.split(' ')[0] || 'unknown';
    
    // 询问描述（可选）
    let description = await vscode.window.showInputBox({
      prompt: '输入修改说明（可选）',
      placeHolder: '例如: 修复登录bug'
    });
    
    const commentSyntax = AIDetector.getCommentSyntax(editor.document.languageId);
    const formattedDate = new Date().toISOString().split('T')[0];
    
    if (markStyle.value === 'block') {
      // 块级标记格式
      const desc = description || '';
      const startMark = `${commentSyntax} @human-start by ${author} ${formattedDate}${desc ? ' ' + desc : ''}`;
      const endMark = `${commentSyntax} @human-end`;
      
      // 获取选中代码第一行的缩进
      const firstLineText = editor.document.lineAt(selection.start.line).text;
      const indentMatch = firstLineText.match(/^(\s*)/);
      const indent = indentMatch ? indentMatch[1] : '';
      
      await editor.edit(editBuilder => {
        // 在选中代码开始前插入开始标记（保持相同缩进）
        editBuilder.insert(new vscode.Position(selection.start.line, 0), indent + startMark + '\n');
        // 在选中代码结束后插入结束标记（保持相同缩进）
        const endLineText = editor.document.lineAt(selection.end.line).text;
        editBuilder.insert(new vscode.Position(selection.end.line, endLineText.length), '\n' + indent + endMark);
      });
      
      vscode.window.showInformationMessage(`✅ 已标记代码块为人工编写 (by ${author})`);
    } else {
      // 行内标记格式（保持相同缩进）
      const firstLineText = editor.document.lineAt(selection.start.line).text;
      const indentMatch = firstLineText.match(/^(\s*)/);
      const indent = indentMatch ? indentMatch[1] : '';
      
      const desc = description ? ` ${description}` : '';
      const humanMark = `${commentSyntax} @human-written by ${author} ${formattedDate}${desc}`;
      
      await editor.edit(editBuilder => {
        editBuilder.insert(new vscode.Position(selection.start.line, 0), indent + humanMark + '\n');
      });
      
      vscode.window.showInformationMessage(`✅ 已标记为人工编写代码 (by ${author})`);
    }
    
    await this.gitAnalyzer.analyzeFile(editor.document.fileName);
  }

  async analyzeGitHistory(): Promise<void> {
    vscode.window.showInformationMessage('正在分析Git历史，这可能需要几分钟...');
    await this.gitAnalyzer.analyzeWorkspace();
    vscode.window.showInformationMessage('✅ Git历史分析完成！');
    // 触发统计更新
    this.statsManager.getStats(); // 确保统计已更新
  }

  async smartPaste(): Promise<void> {
    try {
      const editor = vscode.window.activeTextEditor;
      if (!editor) {
        vscode.window.showWarningMessage('没有打开的编辑器');
        return;
      }
      
      const config = vscode.workspace.getConfiguration('aiCodeTracker');
      const clipboardText = await vscode.env.clipboard.readText();
      
      if (!clipboardText || clipboardText.trim() === '') {
        vscode.window.showWarningMessage('剪贴板为空');
        return;
      }
      
      const aiModel = AIDetector.detectSource(clipboardText);
      
      if (aiModel) {
        const selection = editor.selection;
        const startLine = selection.start.line;
        
        let hasMark = false;
        for (let i = Math.max(0, startLine - 5); i <= startLine; i++) {
          if (i >= editor.document.lineCount) break;
          const line = editor.document.lineAt(i).text;
          if (line.includes('[AI-GEN]')) {
            hasMark = true;
            break;
          }
        }
        
        if (!hasMark) {
          const autoMark = config.get('autoMarkAI', false);
          
          if (autoMark) {
            await this.pasteWithAIMark(editor, clipboardText, aiModel);
            vscode.window.showInformationMessage(`✅ 已自动标记为 AI 生成代码 (${aiModel})`);
            return;
          } else {
            const choice = await vscode.window.showInformationMessage(
              `检测到来自 ${aiModel} 的代码，是否标记为AI生成？`,
              '标记为AI代码',
              '不标记',
              '总是自动标记'
            );
            
            if (choice === '标记为AI代码') {
              await this.pasteWithAIMark(editor, clipboardText, aiModel);
              return;
            } else if (choice === '总是自动标记') {
              await this.pasteWithAIMark(editor, clipboardText, aiModel);
              await config.update('autoMarkAI', true, vscode.ConfigurationTarget.Global);
              vscode.window.showInformationMessage('✅ 已启用自动标记');
              return;
            }
          }
        }
      }
      
      // 没有检测到 AI 代码，执行普通粘贴
      await vscode.commands.executeCommand('editor.action.clipboardPasteAction');
      
    } catch (error) {
      console.error('智能粘贴出错:', error);
      await vscode.commands.executeCommand('editor.action.clipboardPasteAction');
    }
  }

  private async pasteWithAIMark(
    editor: vscode.TextEditor,
    clipboardText: string,
    model: string
  ): Promise<void> {
    const selection = editor.selection;
    const markComment = AIDetector.getCommentSyntax(editor.document.languageId);
    const aiMark = `${markComment} [AI-GEN] model=${model} timestamp=${new Date().toISOString()}\n`;
    const finalText = aiMark + clipboardText;
    
    await editor.edit(editBuilder => {
      if (selection.isEmpty) {
        editBuilder.insert(selection.active, finalText);
      } else {
        editBuilder.replace(selection, finalText);
      }
    });
    
    await this.gitAnalyzer.analyzeFile(editor.document.fileName);
  }
}