import * as vscode from 'vscode';
import { MarkPatternManager } from '../core/markPatternManager';
import { AIMarkPattern } from '../types';

export class SettingsCommands {
  private patternManager = MarkPatternManager.getInstance();

  async configureAIMarks(): Promise<void> {
    const options = [
      '📋 查看当前标记模式',
      '➕ 添加自定义标记模式',
      '✏️ 编辑标记模式',
      '🗑️ 删除自定义标记模式',
      '⚙️ 配置标记格式',
      '🔍 测试标记模式'
    ];
    
    const choice = await vscode.window.showQuickPick(options, {
      placeHolder: '选择要执行的操作',
      ignoreFocusOut: true
    });
    
    switch (choice) {
      case '📋 查看当前标记模式':
        await this.showPatterns();
        break;
      case '➕ 添加自定义标记模式':
        await this.addCustomPattern();
        break;
      case '✏️ 编辑标记模式':
        await this.editPattern();
        break;
      case '🗑️ 删除自定义标记模式':
        await this.deletePattern();
        break;
      case '⚙️ 配置标记格式':
        await this.configureMarkFormat();
        break;
      case '🔍 测试标记模式':
        await this.testPattern();
        break;
    }
  }

  private async showPatterns(): Promise<void> {
    const patterns = this.patternManager.getPatterns();
    
    if (patterns.length === 0) {
      vscode.window.showInformationMessage('暂无配置的 AI 标记模式');
      return;
    }
    
    const patternList = patterns.map(p => {
      const status = p.enabled ? '✅' : '⭕';
      return `${status} ${p.name}: ${p.description || '无描述'}\n   模式: ${p.patterns.join(', ')}`;
    }).join('\n\n');
    
    const panel = vscode.window.createWebviewPanel(
      'aiMarkPatterns',
      'AI 标记模式配置',
      vscode.ViewColumn.One,
      { enableScripts: true }
    );
    
    panel.webview.html = this.getPatternsWebview(patterns);
  }

  private async addCustomPattern(): Promise<void> {
    const name = await vscode.window.showInputBox({
      prompt: '输入标记模式名称',
      placeHolder: '例如: my-ai-tool',
      validateInput: (value) => {
        if (!value) return '名称不能为空';
        if (value.includes(' ')) return '名称不能包含空格';
        return null;
      }
    });
    
    if (!name) return;
    
    const patternsInput = await vscode.window.showInputBox({
      prompt: '输入正则表达式模式（多个用逗号分隔）',
      placeHolder: '例如: \\[MY-AI\\], Generated by MyAI, @myai',
      value: `\\[${name.toUpperCase()}\\]`
    });
    
    if (!patternsInput) return;
    
    const patterns = patternsInput.split(',').map(p => p.trim());
    const description = await vscode.window.showInputBox({
      prompt: '输入描述（可选）',
      placeHolder: '例如: 我的自定义 AI 工具生成的代码'
    });
    
    const newPattern: AIMarkPattern = {
      name,
      patterns,
      description: description || undefined,
      enabled: true
    };
    
    this.patternManager.addCustomPattern(newPattern);
    vscode.window.showInformationMessage(`✅ 已添加标记模式: ${name}`);
  }

  private async editPattern(): Promise<void> {
    const patterns = this.patternManager.getPatterns();
    const patternNames = patterns.map(p => `${p.enabled ? '✅' : '⭕'} ${p.name}`);
    
    const selected = await vscode.window.showQuickPick(patternNames, {
      placeHolder: '选择要编辑的标记模式'
    });
    
    if (!selected) return;
    
    const name = selected.replace(/^[✅⭕]\s/, '');
    const pattern = patterns.find(p => p.name === name);
    
    if (!pattern) return;
    
    const action = await vscode.window.showQuickPick([
      '启用/禁用',
      '编辑模式',
      '编辑描述'
    ], {
      placeHolder: `编辑 ${pattern.name}`
    });
    
    if (action === '启用/禁用') {
      this.patternManager.togglePattern(pattern.name, !pattern.enabled);
      vscode.window.showInformationMessage(
        `${pattern.enabled ? '⭕ 已禁用' : '✅ 已启用'} 模式: ${pattern.name}`
      );
    } else if (action === '编辑模式') {
      const newPatterns = await vscode.window.showInputBox({
        prompt: '编辑正则表达式模式（多个用逗号分隔）',
        value: pattern.patterns.join(', ')
      });
      
      if (newPatterns) {
        const updated = {
          ...pattern,
          patterns: newPatterns.split(',').map(p => p.trim())
        };
        this.patternManager.addCustomPattern(updated);
        vscode.window.showInformationMessage(`✅ 已更新模式: ${pattern.name}`);
      }
    } else if (action === '编辑描述') {
      const newDesc = await vscode.window.showInputBox({
        prompt: '编辑描述',
        value: pattern.description || ''
      });
      
      if (newDesc !== undefined) {
        const updated = {
          ...pattern,
          description: newDesc || undefined
        };
        this.patternManager.addCustomPattern(updated);
        vscode.window.showInformationMessage(`✅ 已更新描述: ${pattern.name}`);
      }
    }
  }

  private async deletePattern(): Promise<void> {
    const patterns = this.patternManager.getPatterns();
    const customPatterns = patterns.filter(p => 
      !['deepseek', 'copilot', 'claude', 'chatgpt', 'cursor', 'tabnine', 'codeium', 'generic-ai', 'human'].includes(p.name)
    );
    
    if (customPatterns.length === 0) {
      vscode.window.showInformationMessage('没有可删除的自定义标记模式');
      return;
    }
    
    const selected = await vscode.window.showQuickPick(
      customPatterns.map(p => p.name),
      { placeHolder: '选择要删除的标记模式' }
    );
    
    if (selected) {
      const confirm = await vscode.window.showWarningMessage(
        `确定要删除标记模式 "${selected}" 吗？`,
        '确定',
        '取消'
      );
      
      if (confirm === '确定') {
        this.patternManager.removeCustomPattern(selected);
        vscode.window.showInformationMessage(`🗑️ 已删除标记模式: ${selected}`);
      }
    }
  }

  private async configureMarkFormat(): Promise<void> {
    const config = vscode.workspace.getConfiguration('aiCodeTracker');
    const currentFormat = config.get<string>('markFormat', 'comment');
    
    interface FormatOption extends vscode.QuickPickItem {
      value: string;
    }
    
    const formatOptions: FormatOption[] = [
      { 
        label: '$(comment) 注释格式', 
        description: '// [AI-GEN] model=xxx',
        detail: '使用代码注释格式标记 AI 代码',
        value: 'comment'
      },
      { 
        label: '$(tag) 标签格式', 
        description: '[AI-GEN] model=xxx',
        detail: '使用纯文本标签标记 AI 代码',
        value: 'tag'
      },
      { 
        label: '$(code) 块标记格式', 
        description: '// @ai-generated-start by {author} {date}',
        detail: '使用开始/结束标记包裹 AI 代码块',
        value: 'block'
      },
      { 
        label: '$(pencil) 自定义格式', 
        description: '使用自定义模板',
        detail: '自定义标记格式',
        value: 'custom'
      }
    ];
    
    const formatMap: Record<string, string> = {
      'comment': '注释格式',
      'tag': '标签格式',
      'block': '块标记格式',
      'custom': '自定义格式'
    };
    
    const selected = await vscode.window.showQuickPick(formatOptions, {
      placeHolder: `当前格式: ${formatMap[currentFormat]}`,
      ignoreFocusOut: true
    });
    
    if (!selected) return;
    
    await config.update('markFormat', selected.value, vscode.ConfigurationTarget.Global);
    
    if (selected.value === 'custom') {
      const currentTemplate = config.get<string>('customMarkTemplate', '// [AI-GEN] model={model} timestamp={timestamp}');
      const template = await vscode.window.showInputBox({
        prompt: '自定义标记模板',
        placeHolder: '支持变量: {model}, {timestamp}, {date}, {author}',
        value: currentTemplate,
        validateInput: (value) => {
          if (!value || value.trim() === '') {
            return '模板不能为空';
          }
          return null;
        }
      });
      
      if (template) {
        await config.update('customMarkTemplate', template, vscode.ConfigurationTarget.Global);
        vscode.window.showInformationMessage(`✅ 已设置自定义模板`);
      } else {
        await config.update('markFormat', currentFormat, vscode.ConfigurationTarget.Global);
        return;
      }
    } else if (selected.value === 'block') {
      // 询问是否自动使用当前用户作为作者
      const useCurrentUser = await vscode.window.showQuickPick(
        ['使用当前 Git 用户', '手动输入', '不包含作者'],
        { placeHolder: '块标记作者设置' }
      );
      
      if (useCurrentUser === '使用当前 Git 用户') {
        // 获取当前 Git 用户
        const { getCurrentGitUser } = await import('../utils/git');
        const user = await getCurrentGitUser();
        const author = user.name.split('@')[0] || user.email.split('@')[0];
        await config.update('blockMarkAuthor', author, vscode.ConfigurationTarget.Global);
        vscode.window.showInformationMessage(`✅ 块标记将使用作者: ${author}`);
      }
    }
    
    vscode.window.showInformationMessage(`✅ 已设置标记格式为: ${formatMap[selected.value]}`);
  }

  private async testPattern(): Promise<void> {
    const editor = vscode.window.activeTextEditor;
    if (!editor) {
      vscode.window.showWarningMessage('请先打开一个文件进行测试');
      return;
    }
    
    const selection = editor.selection;
    let textToTest = '';
    
    if (!selection.isEmpty) {
      textToTest = editor.document.getText(selection);
    } else {
      textToTest = await vscode.window.showInputBox({
        prompt: '输入要测试的文本',
        placeHolder: '输入代码或标记进行测试'
      }) || '';
    }
    
    if (!textToTest) return;
    
    const result = this.patternManager.detectMark(textToTest);
    
    if (result) {
      vscode.window.showInformationMessage(
        `✅ 检测到标记: ${result.name}\n匹配模式: ${result.matchedPattern}`
      );
    } else {
      vscode.window.showWarningMessage('未检测到任何 AI 标记');
      
      const addMark = await vscode.window.showInformationMessage(
        '是否添加 AI 标记？',
        '添加标记',
        '取消'
      );
      
      if (addMark === '添加标记') {
        const model = await vscode.window.showInputBox({
          prompt: '选择 AI 模型',
          placeHolder: 'deepseek, copilot, chatgpt...',
          value: 'ai'
        });
        
        if (model) {
          const mark = this.patternManager.generateAIMark(
            editor.document.languageId,
            model
          );
          
          await editor.edit(editBuilder => {
            if (!selection.isEmpty) {
              editBuilder.insert(selection.start, mark + '\n');
            } else {
              editBuilder.insert(editor.selection.active, mark + '\n');
            }
          });
          
          vscode.window.showInformationMessage(`✅ 已添加 AI 标记`);
        }
      }
    }
  }

  private getPatternsWebview(patterns: AIMarkPattern[]): string {
    const patternsHtml = patterns.map(p => `
      <div class="pattern-card ${p.enabled ? 'enabled' : 'disabled'}">
        <div class="pattern-header">
          <span class="pattern-name">${this.escapeHtml(p.name)}</span>
          <span class="pattern-status">${p.enabled ? '✅ 已启用' : '⭕ 已禁用'}</span>
        </div>
        ${p.description ? `<div class="pattern-desc">${this.escapeHtml(p.description)}</div>` : ''}
        <div class="pattern-patterns">
          <strong>匹配模式:</strong>
          <ul>
            ${p.patterns.map(pat => `<li><code>${this.escapeHtml(pat)}</code></li>`).join('')}
          </ul>
        </div>
      </div>
    `).join('');
    
    return `<!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <style>
        body {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
          padding: 20px;
          background: #1e1e1e;
          color: #d4d4d4;
        }
        h1 {
          color: #4ec9b0;
          border-bottom: 2px solid #4ec9b0;
          padding-bottom: 10px;
        }
        .pattern-card {
          background: #2d2d30;
          border-radius: 8px;
          padding: 15px;
          margin-bottom: 15px;
          border-left: 4px solid #4ec9b0;
        }
        .pattern-card.disabled {
          border-left-color: #888;
          opacity: 0.7;
        }
        .pattern-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 10px;
        }
        .pattern-name {
          font-size: 1.2em;
          font-weight: bold;
          color: #4ec9b0;
        }
        .pattern-desc {
          color: #888;
          margin-bottom: 10px;
          font-style: italic;
        }
        .pattern-patterns {
          margin-top: 10px;
          font-size: 0.9em;
        }
        .pattern-patterns ul {
          margin: 5px 0 0 20px;
        }
        code {
          background: #1e1e1e;
          padding: 2px 6px;
          border-radius: 4px;
          font-family: 'Consolas', monospace;
          color: #ce9178;
        }
        .info {
          background: #007acc;
          padding: 10px;
          border-radius: 4px;
          margin-bottom: 20px;
        }
      </style>
    </head>
    <body>
      <h1>🤖 AI 标记模式配置</h1>
      <div class="info">
        <strong>💡 提示:</strong> 你可以添加自定义正则表达式模式来匹配项目中已有的 AI 代码标记。
        支持多种格式的标记，插件会自动识别并统计。
      </div>
      ${patternsHtml}
    </body>
    </html>`;
  }

  private escapeHtml(text: string): string {
    const map: Record<string, string> = {
      '&': '&amp;',
      '<': '&lt;',
      '>': '&gt;',
      '"': '&quot;',
      "'": '&#039;'
    };
    return text.replace(/[&<>"']/g, m => map[m]);
  }
}