import * as vscode from 'vscode';
import { AIMarkPattern, ParsedAIMark } from '../types';

// 预定义的 AI 标记模式（扩展版）
const DEFAULT_AI_PATTERNS: AIMarkPattern[] = [
  {
    name: 'deepseek',
    patterns: [
      '\\[AI-GEN\\]\\s*model=deepseek',
      '\\[DEEPSEEK\\]',
      'Generated by DeepSeek',
      '@deepseek',
      'deepseek-generated'
    ],
    description: 'DeepSeek AI 生成的代码',
    enabled: true
  },
  {
    name: 'copilot',
    patterns: [
      '\\[AI-GEN\\]\\s*model=copilot',
      '\\[GITHUB-COPILOT\\]',
      'Generated by Copilot',
      '@copilot',
      'copilot-generated'
    ],
    description: 'GitHub Copilot 生成的代码',
    enabled: true
  },
  {
    name: 'claude',
    patterns: [
      '\\[AI-GEN\\]\\s*model=claude',
      '\\[CLAUDE\\]',
      'Generated by Claude',
      '@claude',
      'claude-generated',
      'Anthropic'
    ],
    description: 'Claude AI 生成的代码',
    enabled: true
  },
  {
    name: 'chatgpt',
    patterns: [
      '\\[AI-GEN\\]\\s*model=chatgpt',
      '\\[CHATGPT\\]',
      'Generated by ChatGPT',
      'Generated by GPT',
      '@openai',
      'openai-generated'
    ],
    description: 'ChatGPT/OpenAI 生成的代码',
    enabled: true
  },
  {
    name: 'cursor',
    patterns: [
      '\\[AI-GEN\\]\\s*model=cursor',
      '\\[CURSOR\\]',
      'Generated by Cursor',
      '@cursor'
    ],
    description: 'Cursor AI 生成的代码',
    enabled: true
  },
  {
    name: 'custom-start-end',
    patterns: [
      '//\\s*@ai-generated-start\\s+by\\s+(\\w+)\\s+(\\d{4}-\\d{2}-\\d{2})',
      '#\\s*@ai-generated-start\\s+by\\s+(\\w+)\\s+(\\d{4}-\\d{2}-\\d{2})',
      '<!--\\s*@ai-generated-start\\s+by\\s+(\\w+)\\s+(\\d{4}-\\d{2}-\\d{2})\\s*-->'
    ],
    description: '自定义开始标记格式: @ai-generated-start by {author} {date}',
    enabled: true,
    extractAuthor: true,
    authorPattern: 'by\\s+(\\w+)',
    extractTool: true,
    toolPattern: 'by\\s+(\\w+)'
  },
  {
    name: 'custom-end',
    patterns: [
      '//\\s*@ai-generated-end',
      '#\\s*@ai-generated-end',
      '<!--\\s*@ai-generated-end\\s*-->'
    ],
    description: '自定义结束标记',
    enabled: true
  },
  {
    name: 'generic-ai',
    patterns: [
      '\\[AI-GEN\\]',
      '\\[AI\\]',
      'AI-generated',
      'generated by AI',
      '@ai-generated',
      '// AI:',
      '# AI:',
      '<!-- AI -->'
    ],
    description: '通用 AI 代码标记',
    enabled: true
  },
  {
    name: 'human',
    patterns: [
      '\\[HUMAN\\]',
      '\\[MANUAL\\]',
      'human-written',
      '@human'
    ],
    description: '人工编写代码标记',
    enabled: true
  }
];

export class MarkPatternManager {
  private static instance: MarkPatternManager;
  private patterns: AIMarkPattern[] = [];
  private compiledPatterns: Map<string, RegExp[]> = new Map();
  private startPatterns: RegExp[] = [];
  private endPatterns: RegExp[] = [];

  private constructor() {
    this.loadPatterns();
  }

  static getInstance(): MarkPatternManager {
    if (!MarkPatternManager.instance) {
      MarkPatternManager.instance = new MarkPatternManager();
    }
    return MarkPatternManager.instance;
  }

  // 加载配置模式
  loadPatterns(): void {
    const config = vscode.workspace.getConfiguration('aiCodeTracker');
    const customPatterns = config.get<AIMarkPattern[]>('aiMarkPatterns', []);
    
    // 合并默认模式和自定义模式
    const allPatterns = [...DEFAULT_AI_PATTERNS];
    
    // 添加自定义模式（覆盖同名的默认模式）
    for (const custom of customPatterns) {
      const index = allPatterns.findIndex(p => p.name === custom.name);
      if (index >= 0) {
        allPatterns[index] = { ...allPatterns[index], ...custom };
      } else {
        allPatterns.push(custom);
      }
    }
    
    this.patterns = allPatterns.filter(p => p.enabled);
    this.compilePatterns();
    this.compileBlockPatterns();
  }

  // 编译正则表达式
  private compilePatterns(): void {
    this.compiledPatterns.clear();
    
    for (const pattern of this.patterns) {
      const regexps: RegExp[] = [];
      for (const patternStr of pattern.patterns) {
        try {
          regexps.push(new RegExp(patternStr, 'i'));
        } catch (error) {
          console.error(`无效的正则表达式: ${patternStr}`, error);
        }
      }
      this.compiledPatterns.set(pattern.name, regexps);
    }
  }

  // 编译块标记模式（用于检测代码块边界）
  private compileBlockPatterns(): void {
    this.startPatterns = [];
    this.endPatterns = [];
    
    const startPattern = this.patterns.find(p => p.name === 'custom-start-end');
    const endPattern = this.patterns.find(p => p.name === 'custom-end');
    
    if (startPattern) {
      for (const patternStr of startPattern.patterns) {
        try {
          this.startPatterns.push(new RegExp(patternStr, 'i'));
        } catch (error) {
          console.error(`无效的开始标记正则: ${patternStr}`, error);
        }
      }
    }
    
    if (endPattern) {
      for (const patternStr of endPattern.patterns) {
        try {
          this.endPatterns.push(new RegExp(patternStr, 'i'));
        } catch (error) {
          console.error(`无效的结束标记正则: ${patternStr}`, error);
        }
      }
    }
  }

  // 解析 AI 标记，提取详细信息
  parseMark(line: string): ParsedAIMark | null {
    // 检查是否是 AI 标记
    for (const [name, regexps] of this.compiledPatterns) {
      if (name === 'human') continue;
      
      for (const regex of regexps) {
        const match = regex.exec(line);
        if (match) {
          const result: ParsedAIMark = {
            type: 'ai',
            rawText: line,
            matchedPattern: match[0]
          };
          
          // 尝试提取工具名
          const pattern = this.patterns.find(p => p.name === name);
          if (pattern?.extractTool && pattern.toolPattern) {
            const toolMatch = line.match(new RegExp(pattern.toolPattern, 'i'));
            if (toolMatch) {
              result.tool = toolMatch[1];
            } else {
              result.tool = name;
            }
          } else {
            result.tool = name;
          }
          
          // 尝试提取作者
          if (pattern?.extractAuthor && pattern.authorPattern) {
            const authorMatch = line.match(new RegExp(pattern.authorPattern, 'i'));
            if (authorMatch) {
              result.author = authorMatch[1];
            }
          }
          
          // 尝试提取时间戳
          const dateMatch = line.match(/(\d{4}-\d{2}-\d{2})/);
          if (dateMatch) {
            result.timestamp = new Date(dateMatch[1]);
          }
          
          return result;
        }
      }
    }
    
    // 检查是否是 Human 标记
    const humanPatterns = this.compiledPatterns.get('human');
    if (humanPatterns) {
      for (const regex of humanPatterns) {
        const match = regex.exec(line);
        if (match) {
          const result: ParsedAIMark = {
            type: 'human',
            rawText: line,
            matchedPattern: match[0]
          };
          
          // 尝试提取作者
          const authorMatch = line.match(/author[=\s]+(\w+)/i);
          if (authorMatch) {
            result.author = authorMatch[1];
          }
          
          return result;
        }
      }
    }
    
    return null;
  }

  // 检测文本中的 AI 标记（增强版）
  detectMark(text: string): { name: string; matchedPattern: string; parsed?: ParsedAIMark } | null {
    const lines = text.split('\n');
    
    for (const line of lines) {
      const parsed = this.parseMark(line);
      if (parsed && parsed.type === 'ai') {
        return {
          name: parsed.tool || 'unknown',
          matchedPattern: parsed.matchedPattern,
          parsed
        };
      }
    }
    
    return null;
  }

  // 检查是否是 AI 代码块的开始标记
  isStartMark(line: string): ParsedAIMark | null {
    for (const regex of this.startPatterns) {
      const match = regex.exec(line);
      if (match) {
        const parsed: ParsedAIMark = {
          type: 'ai',
          rawText: line,
          matchedPattern: match[0]
        };
        
        // 提取作者
        const authorMatch = line.match(/by\s+(\w+)/i);
        if (authorMatch) {
          parsed.author = authorMatch[1];
        }
        
        // 提取日期
        const dateMatch = line.match(/(\d{4}-\d{2}-\d{2})/);
        if (dateMatch) {
          parsed.timestamp = new Date(dateMatch[1]);
        }
        
        return parsed;
      }
    }
    return null;
  }

  // 检查是否是 AI 代码块的结束标记
  isEndMark(line: string): boolean {
    for (const regex of this.endPatterns) {
      if (regex.test(line)) {
        return true;
      }
    }
    return false;
  }

  // 检查行是否包含 AI 标记
  hasAIMark(line: string): boolean {
    const parsed = this.parseMark(line);
    return parsed !== null && parsed.type === 'ai';
  }

  // 检查行是否包含 Human 标记
  hasHumanMark(line: string): boolean {
    const parsed = this.parseMark(line);
    return parsed !== null && parsed.type === 'human';
  }

  // 获取 AI 标记的模型名称
  getModelName(line: string): string | null {
    const parsed = this.parseMark(line);
    return parsed?.tool || null;
  }

  // 生成 AI 标记（支持块标记）
  generateAIMark(languageId: string, model: string, options?: {
    format?: 'comment' | 'tag' | 'custom' | 'block';
    template?: string;
    author?: string;
    date?: Date;
  }): string {
    const config = vscode.workspace.getConfiguration('aiCodeTracker');
    const format = options?.format || config.get('markFormat', 'comment');
    const customTemplate = options?.template || config.get('customMarkTemplate');
    
    const timestamp = options?.date || new Date();
    const modelName = model || config.get('defaultModel', 'ai');
    const author = options?.author || '';
    
    const formattedDate = timestamp.toISOString().split('T')[0];
    
    switch (format) {
      case 'tag':
        return `[AI-GEN] model=${modelName} timestamp=${timestamp.toISOString()}`;
      
      case 'block':
        // 生成块标记格式
        const commentSyntax = this.getCommentSyntax(languageId);
        const authorStr = author ? ` by ${author}` : '';
        const dateStr = ` ${formattedDate}`;
        return `${commentSyntax} @ai-generated-start${authorStr}${dateStr}`;
      
      case 'custom':
        if (customTemplate) {
          return customTemplate
            .replace(/\{model\}/g, modelName)
            .replace(/\{timestamp\}/g, timestamp.toISOString())
            .replace(/\{date\}/g, formattedDate)
            .replace(/\{author\}/g, author);
        }
        // fallback to comment format
        return this.getCommentMark(languageId, modelName, timestamp, author);
      
      default:
        return this.getCommentMark(languageId, modelName, timestamp, author);
    }
  }

  // 生成结束标记
  generateEndMark(languageId: string): string {
    const commentSyntax = this.getCommentSyntax(languageId);
    return `${commentSyntax} @ai-generated-end`;
  }

  // 生成注释格式的标记
  private getCommentMark(languageId: string, model: string, timestamp: Date, author?: string): string {
    const commentSyntax = this.getCommentSyntax(languageId);
    const dateStr = timestamp.toISOString().split('T')[0];
    const authorStr = author ? ` by ${author}` : '';
    return `${commentSyntax} [AI-GEN] model=${model}${authorStr} timestamp=${timestamp.toISOString()}`;
  }

  // 生成 Human 标记
  generateHumanMark(languageId: string, author: string): string {
    const commentSyntax = this.getCommentSyntax(languageId);
    const timestamp = new Date().toISOString();
    return `${commentSyntax} [HUMAN] author=${author} timestamp=${timestamp}`;
  }

  // 获取注释语法
  private getCommentSyntax(languageId: string): string {
    const syntax: Record<string, string> = {
      'javascript': '//',
      'typescript': '//',
      'python': '#',
      'java': '//',
      'c': '//',
      'cpp': '//',
      'go': '//',
      'rust': '//',
      'ruby': '#',
      'php': '//',
      'html': '<!--',
      'css': '/*',
      'json': '//',
      'vue': '<!--',
      'jsx': '//',
      'tsx': '//'
    };
    return syntax[languageId] || '//';
  }

  // 获取所有可用的标记模式
  getPatterns(): AIMarkPattern[] {
    return this.patterns;
  }

  // 添加自定义模式
  addCustomPattern(pattern: AIMarkPattern): void {
    const config = vscode.workspace.getConfiguration('aiCodeTracker');
    const current = config.get<AIMarkPattern[]>('aiMarkPatterns', []);
    const existing = current.findIndex(p => p.name === pattern.name);
    
    if (existing >= 0) {
      current[existing] = pattern;
    } else {
      current.push(pattern);
    }
    
    config.update('aiMarkPatterns', current, vscode.ConfigurationTarget.Global);
    this.loadPatterns();
  }

  // 删除自定义模式
  removeCustomPattern(patternName: string): void {
    const config = vscode.workspace.getConfiguration('aiCodeTracker');
    const current = config.get<AIMarkPattern[]>('aiMarkPatterns', []);
    const filtered = current.filter(p => p.name !== patternName);
    config.update('aiMarkPatterns', filtered, vscode.ConfigurationTarget.Global);
    this.loadPatterns();
  }

  // 启用/禁用模式
  togglePattern(patternName: string, enabled: boolean): void {
    const config = vscode.workspace.getConfiguration('aiCodeTracker');
    const current = config.get<AIMarkPattern[]>('aiMarkPatterns', []);
    const pattern = current.find(p => p.name === patternName);
    
    if (pattern) {
      pattern.enabled = enabled;
      config.update('aiMarkPatterns', current, vscode.ConfigurationTarget.Global);
    } else {
      const defaultPattern = DEFAULT_AI_PATTERNS.find(p => p.name === patternName);
      if (defaultPattern) {
        const newPattern = { ...defaultPattern, enabled };
        current.push(newPattern);
        config.update('aiMarkPatterns', current, vscode.ConfigurationTarget.Global);
      }
    }
    
    this.loadPatterns();
  }
}