import * as vscode from 'vscode';
import { AIMarkPattern, ParsedAIMark } from '../types';

// 预定义的 AI 标记模式 - 完整版
const DEFAULT_AI_PATTERNS: AIMarkPattern[] = [
  // ==================== 头部注释格式 ====================
  {
    name: 'jsdoc-header',
    patterns: [
      '/\\*\\*\\s*\\n\\s*\\*\\s*@ai-generated\\s+by\\s+(\\w+)',  // 带作者
      '/\\*\\*\\s*\\n\\s*\\*\\s*@ai-generated\\s*\\n',           // 无作者
      '/\\*\\*\\s*\\*\\s*@ai-generated',                          // 单行
    ],
    description: 'JSDoc 头部注释: /** @ai-generated by [name] @date xxx @description xxx */',
    enabled: true,
    extractAuthor: true,
    authorPattern: '@ai-generated\\s+by\\s+(\\w+)',
    extractTool: true,
    toolPattern: '@ai-generated'
  },
  
  // ==================== Vue/HTML 头部注释 ====================
  {
    name: 'html-header',
    patterns: [
      '<!--\\s*\\n\\s*@ai-generated\\s+by\\s+(\\w+)',           // Vue/HTML 格式
      '<!--\\s*@ai-generated\\s+by\\s+(\\w+)',                  // 单行
      '<!--\\s*@ai-generated\\s*-->',                           // 简单格式
    ],
    description: 'HTML/Vue 头部注释: <!-- @ai-generated by [name] @date xxx @description xxx -->',
    enabled: true,
    extractAuthor: true,
    authorPattern: '@ai-generated\\s+by\\s+(\\w+)',
    extractTool: true,
    toolPattern: '@ai-generated'
  },
  
  // ==================== Python/Shell 头部注释 ====================
  {
    name: 'hash-header',
    patterns: [
      '^"""\\s*\\n@ai-generated\\s+by\\s+(\\w+)',               // Python docstring
      '^#\\s*@ai-generated\\s+by\\s+(\\w+)',                    // Shell/Python 单行
      '^"""\\s*@ai-generated',                                  // Python docstring 单行
    ],
    description: 'Python/Shell 头部: """ @ai-generated by [name] @date xxx """ 或 # @ai-generated by [name]',
    enabled: true,
    extractAuthor: true,
    authorPattern: '@ai-generated\\s+by\\s+(\\w+)',
    extractTool: true,
    toolPattern: '@ai-generated'
  },
  
  // ==================== CSS 头部注释 ====================
  {
    name: 'css-header',
    patterns: [
      '/\\*\\s*\\n\\s*\\*\\s*@ai-generated\\s+by\\s+(\\w+)',    // CSS 格式
      '/\\*\\s*@ai-generated\\s+by\\s+(\\w+)',                  // 单行
    ],
    description: 'CSS 头部注释: /* @ai-generated by [name] @date xxx */',
    enabled: true,
    extractAuthor: true,
    authorPattern: '@ai-generated\\s+by\\s+(\\w+)',
    extractTool: true,
    toolPattern: '@ai-generated'
  },
  
  // ==================== 行内注释格式 ====================
  {
    name: 'inline-comment',
    patterns: [
      '//\\s*@ai-generated:\\s*\\d{4}-\\d{2}-\\d{2}\\s+.*',     // 行内注释格式
      '//\\s*@ai-generated\\s+by\\s+(\\w+):\\s*\\d{4}-\\d{2}-\\d{2}', // 带作者
      '#\\s*@ai-generated:\\s*\\d{4}-\\d{2}-\\d{2}\\s+.*',      // Python 行内
      '<!--\\s*@ai-generated:\\s*\\d{4}-\\d{2}-\\d{2}\\s+.*-->', // HTML 行内
      '\\/\\*\\s*@ai-generated:\\s*\\d{4}-\\d{2}-\\d{2}\\s+.*\\*\\/', // CSS 行内
    ],
    description: '行内注释: // @ai-generated: YYYY-MM-DD 修改说明',
    enabled: true,
    extractAuthor: true,
    authorPattern: '@ai-generated\\s+by\\s+(\\w+)|@ai-generated:\\s*(\\w+)?',
    extractTool: true,
    toolPattern: '@ai-generated'
  },
  
  // ==================== 块注释开始标记 ====================
  {
    name: 'block-start',
    patterns: [
      '//\\s*@ai-generated-start\\s+by\\s+(\\w+)\\s+(\\d{4}-\\d{2}-\\d{2})\\s+(.+)',  // 完整格式
      '//\\s*@ai-generated-start\\s+by\\s+(\\w+)\\s+(\\d{4}-\\d{2}-\\d{2})',         // 带作者和日期
      '//\\s*@ai-generated-start\\s+(\\d{4}-\\d{2}-\\d{2})\\s+(.+)',                 // 带日期和说明
      '//\\s*@ai-generated-start\\s+(.+)',                                           // 只有说明
      '//\\s*@ai-generated-start',                                                   // 无参数
      '#\\s*@ai-generated-start',                                                    // Python 格式
      '<!--\\s*@ai-generated-start',                                                 // HTML/Vue 格式
      '--\\s*@ai-generated-start',                                                   // SQL 格式
      '/\\*\\s*@ai-generated-start',                                                 // CSS 格式
    ],
    description: '块开始标记: // @ai-generated-start by [name] YYYY-MM-DD 说明',
    enabled: true,
    extractAuthor: true,
    authorPattern: '@ai-generated-start\\s+by\\s+(\\w+)',
    extractTool: true,
    toolPattern: '@ai-generated'
  },
  
  // ==================== 块注释结束标记 ====================
  {
    name: 'block-end',
    patterns: [
      '//\\s*@ai-generated-end',
      '#\\s*@ai-generated-end',
      '<!--\\s*@ai-generated-end\\s*-->',
      '--\\s*@ai-generated-end',
      '/\\*\\s*@ai-generated-end\\s*\\*/',
    ],
    description: '块结束标记: // @ai-generated-end',
    enabled: true
  },
  
  // ==================== Vue/JSX 行内注释 ====================
  {
    name: 'jsx-inline',
    patterns: [
      '\\{/\\*\\s*@ai-generated:\\s*\\d{4}-\\d{2}-\\d{2}\\s+.*\\*\\/\\}',  // JSX 行内
    ],
    description: 'JSX 行内注释: {/* @ai-generated: YYYY-MM-DD 说明 */}',
    enabled: true
  },
  
  // ==================== SQL 注释 ====================
  {
    name: 'sql-comment',
    patterns: [
      '--\\s*@ai-generated:\\s*\\d{4}-\\d{2}-\\d{2}\\s+.*',   // SQL 行内
      '--\\s*@ai-generated-start',                            // SQL 块开始
      '--\\s*@ai-generated-end',                              // SQL 块结束
      '/\\*\\s*@ai-generated\\s*\\*/',                        // SQL 块注释
    ],
    description: 'SQL 注释: -- @ai-generated: YYYY-MM-DD 说明',
    enabled: true
  },
  
  // ==================== JSON 标记（通过 .generated 文件）====================
  {
    name: 'json-generated-file',
    patterns: [
      '\\.generated$',                                        // 文件名后缀
    ],
    description: 'JSON 文件通过 .generated 标记文件标识',
    enabled: true
  },
  
  // ==================== 通用 AI 标记 ====================
  {
    name: 'generic-ai',
    patterns: [
      '@ai-generated',
      '\\[AI-GEN\\]',
      '\\[AI\\]',
      'AI-generated',
      'generated by AI',
    ],
    description: '通用 AI 代码标记',
    enabled: true,
    extractTool: true,
    toolPattern: '@ai-generated|\\[AI-GEN\\]'
  },
  
  // ==================== Human 标记 ====================
  {
    name: 'human',
    patterns: [
      '@human',
      '\\[HUMAN\\]',
      '\\[MANUAL\\]',
      'human-written',
    ],
    description: '人工编写代码标记',
    enabled: true
  },
  // 新增：Human 块开始标记
  {
    name: 'human-block-start',
    patterns: [
      '//\\s*@human-start',
      '#\\s*@human-start',
      '<!--\\s*@human-start',
      '--\\s*@human-start',
      '/\\*\\s*@human-start',
    ],
    description: '人工编写代码块开始标记: // @human-start',
    enabled: true
  },
  // 新增：Human 块结束标记
  {
    name: 'human-block-end',
    patterns: [
      '//\\s*@human-end',
      '#\\s*@human-end',
      '<!--\\s*@human-end\\s*-->',
      '--\\s*@human-end',
      '/\\*\\s*@human-end\\s*\\*/',
    ],
    description: '人工编写代码块结束标记: // @human-end',
    enabled: true
  }
];

export class MarkPatternManager {
  private static instance: MarkPatternManager;
  private patterns: AIMarkPattern[] = [];
  private compiledPatterns: Map<string, RegExp[]> = new Map();
  private startPatterns: RegExp[] = [];
  private endPatterns: RegExp[] = [];

  private constructor() {
    this.loadPatterns();
  }

  static getInstance(): MarkPatternManager {
    if (!MarkPatternManager.instance) {
      MarkPatternManager.instance = new MarkPatternManager();
    }
    return MarkPatternManager.instance;
  }

  // 加载配置模式
  loadPatterns(): void {
    const config = vscode.workspace.getConfiguration('aiCodeTracker');
    const customPatterns = config.get<AIMarkPattern[]>('aiMarkPatterns', []);
    
    // 合并默认模式和自定义模式
    const allPatterns = [...DEFAULT_AI_PATTERNS];
    
    // 添加自定义模式（覆盖同名的默认模式）
    for (const custom of customPatterns) {
      const index = allPatterns.findIndex(p => p.name === custom.name);
      if (index >= 0) {
        allPatterns[index] = { ...allPatterns[index], ...custom };
      } else {
        allPatterns.push(custom);
      }
    }
    
    this.patterns = allPatterns.filter(p => p.enabled);
    this.compilePatterns();
    this.compileBlockPatterns();
  }

  // 编译正则表达式
  private compilePatterns(): void {
    this.compiledPatterns.clear();
    
    for (const pattern of this.patterns) {
      const regexps: RegExp[] = [];
      for (const patternStr of pattern.patterns) {
        try {
          regexps.push(new RegExp(patternStr, 'i'));
        } catch (error) {
          console.error(`无效的正则表达式: ${patternStr}`, error);
        }
      }
      this.compiledPatterns.set(pattern.name, regexps);
    }
  }

  // 编译块标记模式
  private compileBlockPatterns(): void {
    this.startPatterns = [];
    this.endPatterns = [];
    
    const startPattern = this.patterns.find(p => p.name === 'block-start');
    const endPattern = this.patterns.find(p => p.name === 'block-end');
    
    if (startPattern) {
      for (const patternStr of startPattern.patterns) {
        try {
          this.startPatterns.push(new RegExp(patternStr, 'i'));
        } catch (error) {
          console.error(`无效的开始标记正则: ${patternStr}`, error);
        }
      }
    }
    
    if (endPattern) {
      for (const patternStr of endPattern.patterns) {
        try {
          this.endPatterns.push(new RegExp(patternStr, 'i'));
        } catch (error) {
          console.error(`无效的结束标记正则: ${patternStr}`, error);
        }
      }
    }
  }

  // 解析 AI 标记，提取详细信息（增强版）
  parseMark(line: string): ParsedAIMark | null {
    // 1. 检查头部注释
    if (this.isHeaderMark(line)) {
      const result: ParsedAIMark = {
        type: 'ai',
        rawText: line,
        matchedPattern: line.match(/@ai-generated[^\n]*/i)?.[0] || '@ai-generated'
      };
      
      // 提取作者
      const authorMatch = line.match(/by\s+(\w+)/i);
      if (authorMatch) {
        result.author = authorMatch[1];
      }
      
      // 提取日期
      const dateMatch = line.match(/(\d{4}-\d{2}-\d{2})/);
      if (dateMatch) {
        result.timestamp = new Date(dateMatch[1]);
      }
      
      // 提取描述
      const descMatch = line.match(/@description\s+(.+?)(?=\n|\*\/|$)/i);
      if (descMatch) {
        result.description = descMatch[1].trim();
      }
      
      return result;
    }
    
    // 2. 检查块开始标记
    const startMark = this.isStartMark(line);
    if (startMark) {
      return startMark;
    }
    
    // 3. 检查行内标记
    if (this.isInlineMark(line)) {
      const result: ParsedAIMark = {
        type: 'ai',
        rawText: line,
        matchedPattern: line.match(/@ai-generated:[^\n]*/i)?.[0] || '@ai-generated'
      };
      
      // 提取作者
      const authorMatch = line.match(/by\s+(\w+)/i);
      if (authorMatch) {
        result.author = authorMatch[1];
      }
      
      // 提取日期
      const dateMatch = line.match(/(\d{4}-\d{2}-\d{2})/);
      if (dateMatch) {
        result.timestamp = new Date(dateMatch[1]);
      }
      
      // 提取描述（冒号后的内容）
      const descMatch = line.match(/@ai-generated:\s*(.+?)(?:\s*$|-->|\*\/)/i);
      if (descMatch) {
        result.description = descMatch[1].trim();
      }
      
      return result;
    }
    
    // 4. 检查通用 AI 标记（修复正则表达式）
    if (line.includes('@ai-generated') || line.includes('[AI-GEN]')) {
      // 分别匹配，避免复杂的正则
      let matchedPattern = '';
      if (line.includes('@ai-generated')) {
        matchedPattern = '@ai-generated';
      } else if (line.includes('[AI-GEN]')) {
        matchedPattern = '[AI-GEN]';
      }
      
      const result: ParsedAIMark = {
        type: 'ai',
        rawText: line,
        matchedPattern: matchedPattern
      };
      
      // 提取作者
      const authorMatch = line.match(/by\s+(\w+)/i);
      if (authorMatch) {
        result.author = authorMatch[1];
      }
      
      // 提取日期
      const dateMatch = line.match(/(\d{4}-\d{2}-\d{2})/);
      if (dateMatch) {
        result.timestamp = new Date(dateMatch[1]);
      }
      
      return result;
    }
    
    // 5. 检查 Human 标记
    if (line.includes('@human') || line.includes('[HUMAN]')) {
      let matchedPattern = '';
      if (line.includes('@human')) {
        matchedPattern = '@human';
      } else if (line.includes('[HUMAN]')) {
        matchedPattern = '[HUMAN]';
      }
      
      const result: ParsedAIMark = {
        type: 'human',
        rawText: line,
        matchedPattern: matchedPattern
      };
      
      // 提取作者
      const authorMatch = line.match(/by\s+(\w+)|author[=\s]+(\w+)/i);
      if (authorMatch) {
        result.author = authorMatch[1] || authorMatch[2];
      }
      
      return result;
    }
    
    return null;
  }

  // 检测文本中的 AI 标记
  detectMark(text: string): { name: string; matchedPattern: string; parsed?: ParsedAIMark } | null {
    const lines = text.split('\n');
    
    for (const line of lines) {
      const parsed = this.parseMark(line);
      if (parsed && parsed.type === 'ai') {
        return {
          name: parsed.tool || 'unknown',
          matchedPattern: parsed.matchedPattern,
          parsed
        };
      }
    }
    
    return null;
  }

  // 检查是否是 AI 代码块的开始标记
  isStartMark(line: string): ParsedAIMark | null {
    for (const regex of this.startPatterns) {
      const match = regex.exec(line);
      if (match) {
        const parsed: ParsedAIMark = {
          type: 'ai',
          rawText: line,
          matchedPattern: match[0]
        };
        
        // 提取作者
        const authorMatch = line.match(/by\s+(\w+)/i);
        if (authorMatch) {
          parsed.author = authorMatch[1];
        }
        
        // 提取日期
        const dateMatch = line.match(/(\d{4}-\d{2}-\d{2})/);
        if (dateMatch) {
          parsed.timestamp = new Date(dateMatch[1]);
        }
        
        // 提取描述
        const descMatch = line.match(/start\s+(?:by\s+\w+\s+\d{4}-\d{2}-\d{2}\s+)?(.+?)$/i);
        if (descMatch && descMatch[1]) {
          parsed.description = descMatch[1].trim();
        }
        
        return parsed;
      }
    }
    return null;
  }

  // 检查是否是 AI 代码块的结束标记
  isEndMark(line: string): boolean {
    for (const regex of this.endPatterns) {
      if (regex.test(line)) {
        return true;
      }
    }
    return false;
  }

  // 检查是否是 Human 代码块的开始标记
  isHumanStartMark(line: string): boolean {
    const humanBlockStartPatterns = this.compiledPatterns.get('human-block-start');
    if (!humanBlockStartPatterns) return false;
    
    for (const regex of humanBlockStartPatterns) {
      if (regex.test(line)) {
        return true;
      }
    }
    return false;
  }

  // 检查是否是 Human 代码块的结束标记
  isHumanEndMark(line: string): boolean {
    const humanBlockEndPatterns = this.compiledPatterns.get('human-block-end');
    if (!humanBlockEndPatterns) return false;
    
    for (const regex of humanBlockEndPatterns) {
      if (regex.test(line)) {
        return true;
      }
    }
    return false;
  }

  // 统一检测块级标记
  detectBlockMark(line: string): { type: 'ai' | 'human'; isStart: boolean } | null {
    // 检查 AI 开始
    if (this.isStartMark(line)) {
      return { type: 'ai', isStart: true };
    }
    // 检查 AI 结束
    if (this.isEndMark(line)) {
      return { type: 'ai', isStart: false };
    }
    // 检查 Human 开始
    if (this.isHumanStartMark(line)) {
      return { type: 'human', isStart: true };
    }
    // 检查 Human 结束
    if (this.isHumanEndMark(line)) {
      return { type: 'human', isStart: false };
    }
    return null;
  }

  /**
   * 检查文本是否包含 AI 标记（支持多行内容）
   * @param content 可以是单行字符串或多行文本
   */
  hasAIMark(content: string): boolean {
    // 如果是多行内容，逐行检查
    const lines = content.split('\n');
    for (const line of lines) {
      // 1. 检查头部注释（JSDoc、HTML、Python等）
      if (this.isHeaderMark(line)) {
        return true;
      }
      
      // 2. 检查块开始标记
      if (this.isStartMark(line)) {
        return true;
      }
      
      // 3. 检查行内注释
      const inlinePatterns = this.compiledPatterns.get('inline-comment');
      if (inlinePatterns) {
        for (const regex of inlinePatterns) {
          if (regex.test(line)) {
            return true;
          }
        }
      }
      
      // 4. 检查通用 AI 标记
      const genericPatterns = this.compiledPatterns.get('generic-ai');
      if (genericPatterns) {
        for (const regex of genericPatterns) {
          if (regex.test(line)) {
            return true;
          }
        }
      }
      
      // 5. 检查 JSDoc 头部标记
      const jsdocPatterns = this.compiledPatterns.get('jsdoc-header');
      if (jsdocPatterns) {
        for (const regex of jsdocPatterns) {
          if (regex.test(line)) {
            return true;
          }
        }
      }
      
      // 6. 检查 HTML 头部标记
      const htmlPatterns = this.compiledPatterns.get('html-header');
      if (htmlPatterns) {
        for (const regex of htmlPatterns) {
          if (regex.test(line)) {
            return true;
          }
        }
      }
      
      // 7. 检查 Python/Shell 头部标记
      const hashPatterns = this.compiledPatterns.get('hash-header');
      if (hashPatterns) {
        for (const regex of hashPatterns) {
          if (regex.test(line)) {
            return true;
          }
        }
      }
      
      // 8. 检查 CSS 头部标记
      const cssPatterns = this.compiledPatterns.get('css-header');
      if (cssPatterns) {
        for (const regex of cssPatterns) {
          if (regex.test(line)) {
            return true;
          }
        }
      }
      
      // 9. 检查 SQL 注释
      const sqlPatterns = this.compiledPatterns.get('sql-comment');
      if (sqlPatterns) {
        for (const regex of sqlPatterns) {
          if (regex.test(line)) {
            return true;
          }
        }
      }
      
      // 10. 检查 JSX 注释
      const jsxPatterns = this.compiledPatterns.get('jsx-inline');
      if (jsxPatterns) {
        for (const regex of jsxPatterns) {
          if (regex.test(line)) {
            return true;
          }
        }
      }

      // 添加直接字符串匹配作为后备
      if (line.includes('@ai-generated') || line.includes('[AI-GEN]')) {
        return true;
      }
    }
    
    return false;
  }

  // 检查是否是头部标记（单行）
  private isHeaderMark(line: string): boolean {
    const trimmed = line.trim();
    // JSDoc 格式: /** @ai-generated ... */
    if (trimmed.startsWith('/**') && line.includes('@ai-generated')) {
      return true;
    }
    
    // HTML/Vue 格式: <!-- @ai-generated ... -->
    if (trimmed.startsWith('<!--') && line.includes('@ai-generated')) {
      return true;
    }
    
    // Python docstring 格式: """ @ai-generated ... """
    if (trimmed.startsWith('"""') && line.includes('@ai-generated')) {
      return true;
    }
    
    // Python/Shell 单行: # @ai-generated ...
    if (trimmed.startsWith('#') && line.includes('@ai-generated')) {
      return true;
    }
    
    // CSS 格式: /* @ai-generated ... */
    if (trimmed.startsWith('/*') && line.includes('@ai-generated')) {
      return true;
    }
    
    // 单行注释格式: // @ai-generated ...
    if (trimmed.startsWith('//') && line.includes('@ai-generated')) {
      return true;
    }
    
    return false;
  }

  // 检查是否是行内标记
  isInlineMark(line: string): boolean {
    // // @ai-generated: YYYY-MM-DD 说明
    if (line.includes('// @ai-generated:')) {
      return true;
    }
    
    // # @ai-generated: YYYY-MM-DD 说明
    if (line.includes('# @ai-generated:')) {
      return true;
    }
    
    // <!-- @ai-generated: YYYY-MM-DD 说明 -->
    if (line.includes('<!-- @ai-generated:')) {
      return true;
    }
    
    // /* @ai-generated: YYYY-MM-DD 说明 */
    if (line.includes('/* @ai-generated:')) {
      return true;
    }
    
    // -- @ai-generated: YYYY-MM-DD 说明 (SQL)
    if (line.includes('-- @ai-generated:')) {
      return true;
    }
    
    return false;
  }

  // 检查行是否包含 Human 标记
  hasHumanMark(line: string): boolean {
    const humanPatterns = this.compiledPatterns.get('human');
    if (!humanPatterns) return false;
    
    for (const regex of humanPatterns) {
      if (regex.test(line)) {
        return true;
      }
    }
    return false;
  }

  /**
   * 检测多行头部注释（增强版）
   * 收集整个注释块的内容后再检测，解决 @ai-generated 在第二行的问题
   */
  detectMultilineHeader(lines: string[]): { startLine: number; endLine: number; type: 'ai' | 'human' } | null {
    const checkLimit = Math.min(50, lines.length);
    
    for (let i = 0; i < checkLimit; i++) {
      const line = lines[i];
      const trimmed = line.trim();
      
      // JSDoc 格式开始: /**
      if (trimmed.startsWith('/**')) {
        // 收集整个多行注释的内容
        let commentContent = '';
        let endLine = i;
        
        for (let j = i; j < Math.min(i + 30, lines.length); j++) {
          commentContent += lines[j] + '\n';
          if (lines[j].includes('*/')) {
            endLine = j;
            break;
          }
        }
        
        // 检查整个注释内容是否包含 AI 标记
        if (this.hasAIMark(commentContent)) {
          return { startLine: i, endLine: endLine, type: 'ai' };
        }
        if (this.hasHumanMark(commentContent)) {
          return { startLine: i, endLine: endLine, type: 'human' };
        }
      }
      
      // HTML/Vue 格式开始: <!--
      if (trimmed.startsWith('<!--')) {
        let commentContent = '';
        let endLine = i;
        
        for (let j = i; j < Math.min(i + 15, lines.length); j++) {
          commentContent += lines[j] + '\n';
          if (lines[j].includes('-->')) {
            endLine = j;
            break;
          }
        }
        
        if (this.hasAIMark(commentContent)) {
          return { startLine: i, endLine: endLine, type: 'ai' };
        }
        if (this.hasHumanMark(commentContent)) {
          return { startLine: i, endLine: endLine, type: 'human' };
        }
      }
      
      // Python docstring 格式开始: """
      if (trimmed.startsWith('"""')) {
        let commentContent = '';
        let endLine = i;
        
        for (let j = i; j < Math.min(i + 20, lines.length); j++) {
          commentContent += lines[j] + '\n';
          if (lines[j].includes('"""') && j > i) {
            endLine = j;
            break;
          }
        }
        
        if (this.hasAIMark(commentContent)) {
          return { startLine: i, endLine: endLine, type: 'ai' };
        }
        if (this.hasHumanMark(commentContent)) {
          return { startLine: i, endLine: endLine, type: 'human' };
        }
      }
      
      // CSS 多行注释开始: /*
      if (trimmed.startsWith('/*') && !trimmed.startsWith('/**')) {
        let commentContent = '';
        let endLine = i;
        
        for (let j = i; j < Math.min(i + 15, lines.length); j++) {
          commentContent += lines[j] + '\n';
          if (lines[j].includes('*/')) {
            endLine = j;
            break;
          }
        }
        
        if (this.hasAIMark(commentContent)) {
          return { startLine: i, endLine: endLine, type: 'ai' };
        }
        if (this.hasHumanMark(commentContent)) {
          return { startLine: i, endLine: endLine, type: 'human' };
        }
      }
      
      // 单行头部: // @ai-generated 或 # @ai-generated
      if ((trimmed.startsWith('//') || trimmed.startsWith('#')) && this.hasAIMark(line)) {
        return { startLine: i, endLine: i, type: 'ai' };
      }
      if ((trimmed.startsWith('//') || trimmed.startsWith('#')) && this.hasHumanMark(line)) {
        return { startLine: i, endLine: i, type: 'human' };
      }
    }
    
    return null;
  }

  // 获取 AI 标记的模型/工具名称
  getModelName(line: string): string | null {
    const parsed = this.parseMark(line);
    return parsed?.tool || null;
  }

  // 生成 AI 标记（根据配置格式）
  generateAIMark(languageId: string, model: string, options?: {
    format?: 'comment' | 'tag' | 'block' | 'custom' | 'header' | 'inline';
    template?: string;
    author?: string;
    date?: Date;
    description?: string;
  }): string {
    const config = vscode.workspace.getConfiguration('aiCodeTracker');
    const format = options?.format || config.get('markFormat', 'comment');
    
    const timestamp = options?.date || new Date();
    const modelName = model || config.get('defaultModel', 'ai');
    const author = options?.author || '';
    const description = options?.description || '';
    
    const formattedDate = timestamp.toISOString().split('T')[0];
    const commentSyntax = this.getCommentSyntax(languageId);
    
    switch (format) {
      case 'header':
        // 头部注释格式
        if (languageId === 'vue' || languageId === 'html') {
          return `<!--\n@ai-generated by ${author}\n@date ${formattedDate}\n@description ${description}\n-->`;
        } else if (languageId === 'python') {
          return `"""\n@ai-generated by ${author}\n@date ${formattedDate}\n@description ${description}\n"""`;
        } else if (languageId === 'css' || languageId === 'less' || languageId === 'scss') {
          return `/*\n * @ai-generated by ${author}\n * @date ${formattedDate}\n * @description ${description}\n */`;
        } else {
          return `/**\n * @ai-generated by ${author}\n * @date ${formattedDate}\n * @description ${description}\n */`;
        }
      
      case 'inline':
        // 行内注释格式
        const inlineDesc = description ? ` ${description}` : '';
        if (languageId === 'vue' || languageId === 'html') {
          return `<!-- @ai-generated: ${formattedDate}${inlineDesc} -->`;
        } else if (languageId === 'python') {
          return `# @ai-generated: ${formattedDate}${inlineDesc}`;
        } else if (languageId === 'sql') {
          return `-- @ai-generated: ${formattedDate}${inlineDesc}`;
        } else {
          return `// @ai-generated: ${formattedDate}${inlineDesc}`;
        }
      
      case 'block':
        // 块标记格式
        const blockDesc = description ? ` ${description}` : '';
        const authorStr = author ? ` by ${author}` : '';
        const startMark = `${commentSyntax} @ai-generated-start${authorStr} ${formattedDate}${blockDesc}`;
        const endMark = `${commentSyntax} @ai-generated-end`;
        return `${startMark}\n\n${endMark}`;
      
      case 'tag':
        return `[AI-GEN] model=${modelName} timestamp=${timestamp.toISOString()}`;
      
      case 'custom':
        const customTemplate = config.get<string>('customMarkTemplate', '// [AI-GEN] model={model} timestamp={timestamp}');
        return customTemplate
          .replace(/\{model\}/g, modelName)
          .replace(/\{timestamp\}/g, timestamp.toISOString())
          .replace(/\{date\}/g, formattedDate)
          .replace(/\{author\}/g, author)
          .replace(/\{description\}/g, description);
      
      default:
        return `${commentSyntax} [AI-GEN] model=${modelName} timestamp=${timestamp.toISOString()}`;
    }
  }

  // 生成结束标记
  generateEndMark(languageId: string): string {
    const commentSyntax = this.getCommentSyntax(languageId);
    return `${commentSyntax} @ai-generated-end`;
  }

  // 生成 Human 标记
  generateHumanMark(languageId: string, author: string): string {
    const commentSyntax = this.getCommentSyntax(languageId);
    const timestamp = new Date().toISOString();
    
    // 根据语言类型选择合适的 Human 标记格式
    if (languageId === 'html' || languageId === 'vue' || languageId === 'markdown') {
      return `<!-- [HUMAN] author=${author} timestamp=${timestamp} -->`;
    } else if (languageId === 'python' || languageId === 'ruby' || languageId === 'yaml') {
      return `# [HUMAN] author=${author} timestamp=${timestamp}`;
    } else if (languageId === 'sql') {
      return `-- [HUMAN] author=${author} timestamp=${timestamp}`;
    } else {
      // JavaScript, TypeScript, Java, C, C++, Go, Rust 等
      return `${commentSyntax} [HUMAN] author=${author} timestamp=${timestamp}`;
    }
  }

  // 获取注释语法
  private getCommentSyntax(languageId: string): string {
    const syntax: Record<string, string> = {
      'javascript': '//',
      'typescript': '//',
      'jsx': '//',
      'tsx': '//',
      'python': '#',
      'java': '//',
      'c': '//',
      'cpp': '//',
      'go': '//',
      'rust': '//',
      'ruby': '#',
      'php': '//',
      'html': '<!--',
      'vue': '<!--',
      'css': '/*',
      'less': '//',
      'scss': '//',
      'json': '//',
      'sql': '--',
      'yaml': '#',
      'yml': '#',
      'shell': '#',
      'bash': '#',
      'markdown': '<!--'
    };
    return syntax[languageId] || '//';
  }

  // 获取所有可用的标记模式
  getPatterns(): AIMarkPattern[] {
    return this.patterns;
  }

  // 添加自定义模式
  addCustomPattern(pattern: AIMarkPattern): void {
    const config = vscode.workspace.getConfiguration('aiCodeTracker');
    const current = config.get<AIMarkPattern[]>('aiMarkPatterns', []);
    const existing = current.findIndex(p => p.name === pattern.name);
    
    if (existing >= 0) {
      current[existing] = pattern;
    } else {
      current.push(pattern);
    }
    
    config.update('aiMarkPatterns', current, vscode.ConfigurationTarget.Global);
    this.loadPatterns();
  }

  // 删除自定义模式
  removeCustomPattern(patternName: string): void {
    const config = vscode.workspace.getConfiguration('aiCodeTracker');
    const current = config.get<AIMarkPattern[]>('aiMarkPatterns', []);
    const filtered = current.filter(p => p.name !== patternName);
    config.update('aiMarkPatterns', filtered, vscode.ConfigurationTarget.Global);
    this.loadPatterns();
  }

  // 启用/禁用模式
  togglePattern(patternName: string, enabled: boolean): void {
    const config = vscode.workspace.getConfiguration('aiCodeTracker');
    const current = config.get<AIMarkPattern[]>('aiMarkPatterns', []);
    const pattern = current.find(p => p.name === patternName);
    
    if (pattern) {
      pattern.enabled = enabled;
      config.update('aiMarkPatterns', current, vscode.ConfigurationTarget.Global);
    } else {
      const defaultPattern = DEFAULT_AI_PATTERNS.find(p => p.name === patternName);
      if (defaultPattern) {
        const newPattern = { ...defaultPattern, enabled };
        current.push(newPattern);
        config.update('aiMarkPatterns', current, vscode.ConfigurationTarget.Global);
      }
    }
    
    this.loadPatterns();
  }
}